<?php

namespace AppBundle\Repository;

/**
 * BoardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardsRepository extends \Doctrine\ORM\EntityRepository
{
}
