<?php

namespace Skelet\UserBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository {
    /**
     * Authorizes user
     * @param string $login
     * @param string $password
     * @return \Skelet\UserBundle\Entity\Users 
     *	If user found returns user, otherwise it returns NULL
     */
    public function signin($login, $password) {
	$em = $this->getEntityManager();

	$user = $em->getRepository("UserBundle:Users")->findOneBy(['login' => $login, 'password' => md5($password)]);

	return $user;
    }
}
