services:
    Users.Authentify:
        class: Skelet\UserBundle\Utils\Authentify
        arguments: [ "@doctrine.orm.entity_manager" ]
    Users.Authorize:
        class: Skelet\UserBundle\Utils\Authorize
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@session" ]
    Users.SignIn:
        class: Skelet\UserBundle\Utils\SignIn
        arguments: ["@service_container"]
    Users.SignUp:
        class: Skelet\UserBundle\Utils\SignUp
        arguments: ["@service_container"]
    Users.SignOut:
        class: Skelet\UserBundle\Utils\SignOut
        arguments: ["@service_container"]
